/* Lakherance Flagship 3D runtime v446 — self-contained WebGL, Benny / Ren / Owl */
(()=>{'use strict';
const $=s=>document.querySelector(s), clamp=(v,a,b)=>Math.max(a,Math.min(b,v)), TAU=Math.PI*2;
const CAMPAIGNS={
 benny:[['River Beginning','Collect 5 logs and repair the river dam.','river'],['Forest Explorer','Find 6 hidden logs and the otter trail.','forest'],['Builder Bay','Carry 7 logs to the marked dam.','builder'],['Duck Family','Guide 5 ducklings to the safe pond.','ducks'],['Lost Cave','Find 6 glowing stones inside the waterfall cave.','cave'],['Mountain River','Cross the rapids and collect 7 branches.','mountain'],['The Big Dam','Build the great dam with 8 heavy logs.','dam'],['Winter Valley','Find 7 winter supplies through the snow.','winter'],['Hidden Island','Swim to the island and recover 8 treasures.','island'],['The Great River','Restore the river with 10 final materials.','finalriver']],
 ren:[['Training Grounds','Complete 4 training marks.','dojo'],['Bamboo Forest','Defeat 5 scouts and reach the shrine.','bamboo'],['Village Rescue','Defeat 6 raiders and rescue the village.','village'],['Mountain Path','Cross the pass and defeat 6 guards.','mountain'],['Enemy Fortress','Open the gate after defeating 7 guards.','fortress'],['Castle Approach','Reach the castle through 7 sentries.','approach'],['Inside the Castle','Find the scroll and defeat 8 guards.','castle'],['Secret Garden','Find 6 seals hidden among the gardens.','garden'],['Final Battle','Defeat 9 elite warriors.','battle'],['The Shogun','Defeat the Shogun and finish Ren’s journey.','shogun']],
 owl:[['Dawn Flight','Fly through 6 wind rings above the valley.','dawn'],['Whispering Forest','Find 7 feathers beneath the ancient trees.','owlforest'],['Cliff Kingdom','Reach 7 high perches across the cliffs.','cliffs'],['Storm Passage','Fly through 7 safe rings in the storm.','storm'],['Moonlit Ruins','Recover 7 moon feathers among the ruins.','ruins'],['Crystal Cave','Find 8 glowing crystals underground.','crystal'],['Waterfall Realm','Cross 8 air currents beside the falls.','falls'],['Snow Peaks','Reach 8 mountain perches through the snow.','snow'],['Aurora Islands','Find 9 sky feathers among floating islands.','aurora'],['Guardian of the Sky','Complete 10 sky rings and return to the Great Nest.','guardian']]
};
const THEMES={river:[.25,.58,.82],forest:[.18,.48,.28],builder:[.28,.62,.74],ducks:[.35,.68,.82],cave:[.10,.18,.28],mountain:[.38,.58,.72],dam:[.22,.52,.70],winter:[.68,.80,.90],island:[.20,.68,.72],finalriver:[.30,.62,.82],dojo:[.64,.34,.25],bamboo:[.12,.34,.20],village:[.55,.26,.20],fortress:[.25,.16,.18],approach:[.52,.25,.32],castle:[.20,.15,.24],garden:[.45,.25,.42],battle:[.34,.10,.12],shogun:[.18,.08,.10],dawn:[.48,.68,.88],owlforest:[.15,.38,.28],cliffs:[.40,.62,.78],storm:[.12,.18,.30],ruins:[.18,.20,.38],crystal:[.16,.20,.32],falls:[.25,.60,.80],snow:[.65,.76,.88],aurora:[.12,.26,.42],guardian:[.22,.38,.58]};
let G=null;
function mat4(){return new Float32Array(16)} function ident(o){o.fill(0);o[0]=o[5]=o[10]=o[15]=1;return o}
function perspective(o,f,a,n,fa){let t=1/Math.tan(f/2),nf=1/(n-fa);o.fill(0);o[0]=t/a;o[5]=t;o[10]=(fa+n)*nf;o[11]=-1;o[14]=2*fa*n*nf;return o}
function mul(o,a,b){let r=new Float32Array(16);for(let c=0;c<4;c++)for(let rr=0;rr<4;rr++)r[c*4+rr]=a[rr]*b[c*4]+a[4+rr]*b[c*4+1]+a[8+rr]*b[c*4+2]+a[12+rr]*b[c*4+3];o.set(r);return o}
function look(o,e,t,u=[0,1,0]){let zx=e[0]-t[0],zy=e[1]-t[1],zz=e[2]-t[2],zl=Math.hypot(zx,zy,zz)||1;zx/=zl;zy/=zl;zz/=zl;let xx=u[1]*zz-u[2]*zy,xy=u[2]*zx-u[0]*zz,xz=u[0]*zy-u[1]*zx,xl=Math.hypot(xx,xy,xz)||1;xx/=xl;xy/=xl;xz/=xl;let yx=zy*xz-zz*xy,yy=zz*xx-zx*xz,yz=zx*xy-zy*xx;ident(o);o[0]=xx;o[1]=yx;o[2]=zx;o[4]=xy;o[5]=yy;o[6]=zy;o[8]=xz;o[9]=yz;o[10]=zz;o[12]=-(xx*e[0]+xy*e[1]+xz*e[2]);o[13]=-(yx*e[0]+yy*e[1]+yz*e[2]);o[14]=-(zx*e[0]+zy*e[1]+zz*e[2]);return o}
function model(o,x,y,z,sx,sy,sz,ry=0){ident(o);let c=Math.cos(ry),s=Math.sin(ry);o[0]=c*sx;o[2]=-s*sx;o[5]=sy;o[8]=s*sz;o[10]=c*sz;o[12]=x;o[13]=y;o[14]=z;return o}
const V=`attribute vec3 p;attribute vec3 n;uniform mat4 m,vp;varying vec3 N;varying vec3 W;void main(){vec4 w=m*vec4(p,1.);W=w.xyz;N=mat3(m)*n;gl_Position=vp*w;}`;
const F=`precision mediump float;varying vec3 N;varying vec3 W;uniform vec3 color;uniform float glow;void main(){vec3 l=normalize(vec3(-.4,.85,.35));float d=max(.18,dot(normalize(N),l));float fog=clamp((55.-length(W))/45.,.25,1.);vec3 c=color*(d+.22)+glow*color*.55;c=mix(vec3(.42,.58,.68),c,fog);gl_FragColor=vec4(c,1.);}`;
function shader(gl,t,s){let x=gl.createShader(t);gl.shaderSource(x,s);gl.compileShader(x);if(!gl.getShaderParameter(x,gl.COMPILE_STATUS))throw Error(gl.getShaderInfoLog(x));return x}
function mesh(gl,kind){let P=[],N=[],I=[];if(kind==='cube'){P=[-1,-1,1,1,-1,1,1,1,1,-1,1,1, 1,-1,-1,-1,-1,-1,-1,1,-1,1,1,-1, -1,1,1,1,1,1,1,1,-1,-1,1,-1, -1,-1,-1,1,-1,-1,1,-1,1,-1,-1,1, 1,-1,1,1,-1,-1,1,1,-1,1,1,1, -1,-1,-1,-1,-1,1,-1,1,1,-1,1,-1];N=[0,0,1,0,0,1,0,0,1,0,0,1, 0,0,-1,0,0,-1,0,0,-1,0,0,-1, 0,1,0,0,1,0,0,1,0,0,1,0, 0,-1,0,0,-1,0,0,-1,0,0,-1,0, 1,0,0,1,0,0,1,0,0,1,0,0, -1,0,0,-1,0,0,-1,0,0,-1,0,0];for(let f=0;f<6;f++){let b=f*4;I.push(b,b+1,b+2,b,b+2,b+3)}}else{let lat=10,lon=14;for(let y=0;y<=lat;y++){let v=y/lat,ph=v*Math.PI;for(let x=0;x<=lon;x++){let u=x/lon,th=u*TAU,nx=Math.sin(ph)*Math.cos(th),ny=Math.cos(ph),nz=Math.sin(ph)*Math.sin(th);P.push(nx,ny,nz);N.push(nx,ny,nz)}}for(let y=0;y<lat;y++)for(let x=0;x<lon;x++){let a=y*(lon+1)+x,b=a+lon+1;I.push(a,b,a+1,b,b+1,a+1)}}let vao={};vao.p=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,vao.p);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(P),gl.STATIC_DRAW);vao.n=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,vao.n);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array(N),gl.STATIC_DRAW);vao.i=gl.createBuffer();gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,vao.i);gl.bufferData(gl.ELEMENT_ARRAY_BUFFER,new Uint16Array(I),gl.STATIC_DRAW);vao.count=I.length;return vao}
function setupGL(canvas){let gl=canvas.getContext('webgl',{antialias:true,alpha:false});if(!gl)throw Error('WebGL unavailable');let pr=gl.createProgram();gl.attachShader(pr,shader(gl,gl.VERTEX_SHADER,V));gl.attachShader(pr,shader(gl,gl.FRAGMENT_SHADER,F));gl.linkProgram(pr);gl.useProgram(pr);gl.enable(gl.DEPTH_TEST);gl.enable(gl.CULL_FACE);return{gl,pr,cube:mesh(gl,'cube'),sphere:mesh(gl,'sphere'),loc:{p:gl.getAttribLocation(pr,'p'),n:gl.getAttribLocation(pr,'n'),m:gl.getUniformLocation(pr,'m'),vp:gl.getUniformLocation(pr,'vp'),color:gl.getUniformLocation(pr,'color'),glow:gl.getUniformLocation(pr,'glow')}}}
function drawMesh(g,me,x,y,z,sx,sy,sz,c,ry=0,glow=0){let {gl,loc}=g,m=mat4();model(m,x,y,z,sx,sy,sz,ry);gl.uniformMatrix4fv(loc.m,false,m);gl.uniform3fv(loc.color,c);gl.uniform1f(loc.glow,glow);gl.bindBuffer(gl.ARRAY_BUFFER,me.p);gl.vertexAttribPointer(loc.p,3,gl.FLOAT,false,0,0);gl.enableVertexAttribArray(loc.p);gl.bindBuffer(gl.ARRAY_BUFFER,me.n);gl.vertexAttribPointer(loc.n,3,gl.FLOAT,false,0,0);gl.enableVertexAttribArray(loc.n);gl.bindBuffer(gl.ELEMENT_ARRAY_BUFFER,me.i);gl.drawElements(gl.TRIANGLES,me.count,gl.UNSIGNED_SHORT,0)}
function tree(g,x,z,s=1,autumn=false){drawMesh(g,g.cube,x,1.5*s,z,.25*s,1.5*s,.25*s,[.28,.15,.07]);let col=autumn?[.65,.16,.08]:[.08,.36,.14];drawMesh(g,g.sphere,x,3.5*s,z,1.5*s,2*s,1.5*s,col);drawMesh(g,g.sphere,x-.8*s,3*s,z+.2,1*s,1.2*s,1*s,col)}
function rock(g,x,z,s=1){drawMesh(g,g.sphere,x,.45*s,z,1.2*s,.65*s,1*s,[.30,.34,.34],.3)}
function water(g,z0=-8){drawMesh(g,g.cube,0,-.25,z0,12,.15,30,[.04,.38,.68],0,.15)}
function benny(g,p,t,moving=false){let walk=moving?Math.sin(t*9):0,bob=moving?Math.abs(Math.sin(t*9))*.07:Math.sin(t*2.4)*.018,fur=[.45,.20,.07],light=[.70,.38,.14];drawMesh(g,g.sphere,p.x,1.15+bob,p.z,.65,.8,.55,fur);drawMesh(g,g.sphere,p.x,2.05+bob,p.z,.55,.52,.52,light);drawMesh(g,g.sphere,p.x-.28,2.38+bob,p.z,.16,.18,.12,fur);drawMesh(g,g.sphere,p.x+.28,2.38+bob,p.z,.16,.18,.12,fur);drawMesh(g,g.cube,p.x-.13,1.82+bob,p.z-.52,.09,.16,.04,[.95,.90,.70]);drawMesh(g,g.cube,p.x+.13,1.82+bob,p.z-.52,.09,.16,.04,[.95,.90,.70]);drawMesh(g,g.sphere,p.x,1.0+bob,p.z+.62,.42,.75,.13,[.24,.12,.06],.2);/* walking paws: opposite front/back pairs swing and lift */let liftL=moving?Math.max(0,walk)*.11:0,liftR=moving?Math.max(0,-walk)*.11:0,zSwing=moving?walk*.22:0;drawMesh(g,g.sphere,p.x-.35,.48+liftL,p.z+zSwing,.18,.25,.18,fur);drawMesh(g,g.sphere,p.x+.35,.48+liftR,p.z-zSwing,.18,.25,.18,fur);drawMesh(g,g.sphere,p.x-.48,1.18+bob+liftR*.45,p.z-.18-zSwing,.16,.28,.16,light);drawMesh(g,g.sphere,p.x+.48,1.18+bob+liftL*.45,p.z-.18+zSwing,.16,.28,.16,light)}
function ren(g,p,t){let armor=[.08,.07,.08],red=[.50,.03,.04],skin=[.65,.42,.28];drawMesh(g,g.cube,p.x,1.3,p.z,.42,.75,.28,armor);drawMesh(g,g.sphere,p.x,2.25,p.z,.34,.38,.34,skin);drawMesh(g,g.sphere,p.x,2.65,p.z,.24,.18,.24,[.03,.025,.03]);drawMesh(g,g.cube,p.x,1.15,p.z+.35,.55,.55,.08,red,.1);let st=Math.sin(t*8)*.18;drawMesh(g,g.cube,p.x-.24,.42+Math.max(0,st),p.z,.14,.48,.14,[.05,.04,.05]);drawMesh(g,g.cube,p.x+.24,.42+Math.max(0,-st),p.z,.14,.48,.14,[.05,.04,.05]);drawMesh(g,g.cube,p.x+.62,1.25,p.z-.12,.06,.06,.9,[.72,.72,.70],-.25)}
function owl(g,p,t){let flap=Math.sin(t*10)*.55,fe=[.78,.68,.52],white=[.90,.88,.78];drawMesh(g,g.sphere,p.x,p.y,p.z,.42,.55,.35,white);drawMesh(g,g.sphere,p.x,p.y+.45,p.z,.36,.34,.32,white);drawMesh(g,g.cube,p.x-.72,p.y,p.z,.65,.08,.32,fe,flap);drawMesh(g,g.cube,p.x+.72,p.y,p.z,.65,.08,.32,fe,-flap);drawMesh(g,g.sphere,p.x-.14,p.y+.52,p.z-.28,.07,.07,.04,[.9,.55,.08],0,1);drawMesh(g,g.sphere,p.x+.14,p.y+.52,p.z-.28,.07,.07,.04,[.9,.55,.08],0,1)}
function env(g,s){let th=THEMES[s.theme]||[.3,.5,.7],gl=g.gl;gl.clearColor(th[0]*.55,th[1]*.65,th[2]*.8,1);gl.clear(gl.COLOR_BUFFER_BIT|gl.DEPTH_BUFFER_BIT);drawMesh(g,g.cube,0,-.7,10,20,.5,45,s.game==='ren'?[.16,.22,.12]:[.18,.42,.18]);if(s.game==='benny')water(g,8);for(let i=0;i<22;i++){let x=((i*7)%19)-9,z=((i*13)%55)-12;if(Math.abs(x-s.p.x)<2&&Math.abs(z-s.p.z)<4)continue;if(i%4===0)rock(g,x,z,.6+(i%3)*.2);else tree(g,x,z,.65+(i%4)*.12,s.game==='ren'&&i%3===0)}if(s.game==='ren'){for(let z=-4;z<45;z+=14){drawMesh(g,g.cube,-5,2,z,.18,2,.18,[.42,.08,.04]);drawMesh(g,g.cube,5,2,z,.18,2,.18,[.42,.08,.04]);drawMesh(g,g.cube,0,3.6,z,5.5,.16,.18,[.42,.08,.04])}}if(s.game==='owl'){for(let i=0;i<9;i++){let x=(i%3-1)*5,z=i*6;drawMesh(g,g.cube,x,1.8,z,2.4,.18,2.4,[.30,.34,.32]);drawMesh(g,g.sphere,x,4.5+(i%2)*2,z,1.3,2.5,1.3,[.34,.40,.42])}}}
function makeTargets(s){s.targets=[];let n=s.need;for(let i=0;i<n;i++){let a=i*2.399,r=5+(i%4)*2.4;s.targets.push({x:Math.cos(a)*r,z:5+i*4+Math.sin(a)*3,y:s.game==='owl'?3+(i%4)*2:.65,got:false})}}
function targetDraw(g,s,t){s.targets.forEach((q,i)=>{if(q.got)return;let c=s.game==='benny'?[.72,.38,.08]:s.game==='ren'?[.85,.14,.08]:[.95,.72,.18];if(s.game==='benny')drawMesh(g,g.cube,q.x,q.y,q.z,.65,.18,.18,c,.3);else if(s.game==='ren')drawMesh(g,g.sphere,q.x,q.y,q.z,.32,.55,.32,c,0,.4);else{let yy=q.y+Math.sin(t*3+i)*.3;drawMesh(g,g.sphere,q.x,yy,q.z,.22,.35,.10,c,0,.8)}})}
function hud(s){$('#f3-title').textContent=`${s.game==='benny'?'🦫 Benny':s.game==='ren'?'⚔️ Ren':'🦉 Owl'} · Level ${s.level+1}`;$('#f3-mission').textContent=CAMPAIGNS[s.game][s.level][0];$('#f3-goal').textContent=CAMPAIGNS[s.game][s.level][1];$('#f3-progress').textContent=`${s.got} / ${s.need}`;$('#f3-hearts').textContent='♥'.repeat(s.hp)+'♡'.repeat(5-s.hp);$('#f3-action').textContent=s.game==='ren'?'ATTACK':s.game==='owl'?'BOOST':'ACTION';$('#f3-jump').textContent=s.game==='ren'?'BLOCK':s.game==='owl'?'DIVE':'JUMP'}
function save(s){localStorage.setItem(`lakherance_flagship_${s.game}`,String(Math.max(+localStorage.getItem(`lakherance_flagship_${s.game}`)||1,s.level+1)))}
function complete(s){s.done=true;save(s);$('#f3-result-title').textContent='Mission Complete';$('#f3-result-sub').textContent=`${CAMPAIGNS[s.game][s.level][0]} · ${s.got}/${s.need}`;$('#f3-result').classList.add('show')}
function loop(now){if(!G||G.stop)return;if(!document.getElementById('screen-flagship3d')?.classList.contains('active')){stop();return}let s=G.s,g=G.g,t=now/1000,dt=Math.min(.035,(now-(s.last||now))/1000);s.last=now;if(!s.paused&&!s.done){let mx=(s.keys.r?1:0)-(s.keys.l?1:0),mz=(s.keys.u?1:0)-(s.keys.d?1:0);s.moving=Math.abs(mx)+Math.abs(mz)>.01;if(s.game==='owl'){s.p.x+=mx*6*dt;s.p.z+=mz*7*dt;s.p.y+=s.vy*dt;s.vy*=.96;s.p.y=clamp(s.p.y,1.5,10)}else{s.p.x+=mx*4.2*dt;s.p.z+=mz*4.5*dt;s.vy-=12*dt;s.p.y+=s.vy*dt;if(s.p.y<0){s.p.y=0;s.vy=0}}s.p.x=clamp(s.p.x,-10,10);s.p.z=clamp(s.p.z,-8,50);for(let q of s.targets){let dy=s.game==='owl'?s.p.y-q.y:0;if(!q.got&&Math.hypot(s.p.x-q.x,s.p.z-q.z,dy)<1.45){q.got=true;s.got++;hud(s);if(s.got>=s.need)complete(s)}}}
 let w=G.canvas.clientWidth,h=G.canvas.clientHeight,dpr=Math.min(devicePixelRatio||1,2),rw=Math.floor(w*dpr),rh=Math.floor(h*dpr);if(G.canvas.width!==rw||G.canvas.height!==rh){G.canvas.width=rw;G.canvas.height=rh;g.gl.viewport(0,0,rw,rh)}let eye=s.game==='owl'?[s.p.x,s.p.y+4,s.p.z-9]:[s.p.x,s.p.y+5,s.p.z-9],tar=[s.p.x,s.game==='owl'?s.p.y:s.p.y+1.2,s.p.z+5],v=mat4(),p=mat4(),vp=mat4();look(v,eye,tar);perspective(p,Math.PI/3,rw/rh,.1,120);mul(vp,p,v);g.gl.useProgram(g.pr);g.gl.uniformMatrix4fv(g.loc.vp,false,vp);env(g,s);targetDraw(g,s,t);if(s.game==='benny')benny(g,{x:s.p.x,z:s.p.z},t,!!s.moving);else if(s.game==='ren')ren(g,{x:s.p.x,z:s.p.z},t);else owl(g,s.p,t);G.raf=requestAnimationFrame(loop)}
function start(game,level=0){if(G)stop();let canvas=$('#f3-canvas'),g;try{g=setupGL(canvas)}catch(e){$('#f3-fallback').style.display='grid';$('#f3-fallback').textContent='This device does not provide WebGL. Please enable hardware acceleration.';return}let cfg=CAMPAIGNS[game][level],need=(+((cfg[1].match(/\d+/)||[])[0])||(/Shogun/.test(cfg[1])?1:5));let s={game,level,theme:cfg[2],need,got:0,hp:5,p:{x:0,y:game==='owl'?4:0,z:-3},vy:0,keys:{},paused:false,done:false,last:0};makeTargets(s);G={canvas,g,s,raf:0,stop:false};$('#f3-result').classList.remove('show');$('#f3-fallback').style.display='none';showScreen('screen-flagship3d');hud(s);G.raf=requestAnimationFrame(loop)}
function stop(){if(!G)return;G.stop=true;cancelAnimationFrame(G.raf);G=null}
function key(k,v){if(G)G.s.keys[k]=v} function action(kind){if(!G||G.s.done)return;let s=G.s;if(s.game==='owl'){if(kind==='action')s.vy=4.8;else s.vy=-5}else if(s.game==='ren'){if(kind==='action'){let q=s.targets.find(q=>!q.got&&Math.hypot(s.p.x-q.x,s.p.z-q.z)<2.7);if(q){q.got=true;s.got++;hud(s);if(s.got>=s.need)complete(s)}}}else if(kind==='jump'&&s.p.y<=.01)s.vy=5.5}
function next(){if(!G)return;let {game,level}=G.s;if(level<9)start(game,level+1);else{$('#f3-result-title').textContent='Adventure Complete';$('#f3-result-sub').textContent='All 10 missions completed.'}}
function levelSelect(game){let unlocked=clamp(+localStorage.getItem(`lakherance_flagship_${game}`)||1,1,10);$('#f3-select-title').textContent=game==='benny'?'🦫 Benny — The Brave Beaver':game==='ren'?'⚔️ Ren — The Samurai':'🦉 Owl — Sky Adventure';let box=$('#f3-levels');box.innerHTML=CAMPAIGNS[game].map((x,i)=>`<button class="f3-level" ${i>=unlocked?'disabled':''} data-i="${i}"><b>${i+1}. ${x[0]}</b><span>${x[1]}</span></button>`).join('');box.querySelectorAll('button:not(:disabled)').forEach(b=>b.addEventListener('click',()=>start(game,+b.dataset.i)));$('#f3-select').dataset.game=game;showScreen('screen-flagship-select')}
function bindHold(id,k){let b=$(id);if(!b)return;['pointerdown'].forEach(ev=>b.addEventListener(ev,e=>{e.preventDefault();key(k,true);b.setPointerCapture?.(e.pointerId)}));['pointerup','pointercancel','pointerleave'].forEach(ev=>b.addEventListener(ev,e=>{key(k,false)}))}
window.LakFlagship={open:levelSelect,start,stop};
window.addEventListener('load',()=>{bindHold('#f3-left','l');bindHold('#f3-right','r');bindHold('#f3-up','u');bindHold('#f3-down','d');$('#f3-action')?.addEventListener('pointerdown',e=>{e.preventDefault();action('action')});$('#f3-jump')?.addEventListener('pointerdown',e=>{e.preventDefault();action('jump')});$('#f3-next')?.addEventListener('click',next);$('#f3-retry')?.addEventListener('click',()=>G&&start(G.s.game,G.s.level));$('#f3-pause')?.addEventListener('click',()=>{if(G){G.s.paused=!G.s.paused;$('#f3-pause').textContent=G.s.paused?'▶':'Ⅱ'}});$('#f3-full')?.addEventListener('click',()=>{let el=$('#screen-flagship3d');if(!document.fullscreenElement)el.requestFullscreen?.();else document.exitFullscreen?.()});window.addEventListener('keydown',e=>{if(!G||/^(INPUT|TEXTAREA|SELECT)$/.test(e.target?.tagName||'')||e.target?.isContentEditable)return;let m={ArrowLeft:'l',a:'l',ArrowRight:'r',d:'r',ArrowUp:'u',w:'u',ArrowDown:'d',s:'d'}[e.key];if(m){key(m,true);e.preventDefault()}if(e.key===' ')action('action')});window.addEventListener('keyup',e=>{if(!G)return;let m={ArrowLeft:'l',a:'l',ArrowRight:'r',d:'r',ArrowUp:'u',w:'u',ArrowDown:'d',s:'d'}[e.key];if(m)key(m,false)})});
})();
